version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Port for your web app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=autopartsdb
    depends_on:
      - mysql
    volumes:
      - ./src/views:/app/src/views          # Mount views correctly for HTML files
      - ./src/public/styles:/app/src/public/styles  # Mount CSS files to the correct static folder
      - ./src/views/images:/app/src/views/images  # Mount images folder correctly

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autopartsdb
      MYSQL_PASSWORD: rootpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"  # Expose port 8080 for phpMyAdmin