const express = require('express');
const register = require('./register');
const login = require('./login');
const changepassword = require('./changepassword');
const brands = require('./cars').brands;
const models = require('./cars').models;
const engines = require('./cars').engines;
const deleteaccount = require('./deleteaccount');
const loggedIn = require('./loggedIn');
const category = require('./category');
const parts = require('./parts').parts;
const partsByCode = require('./parts').partsByCode;
const brandsFilterSelect = require('./parts').brandsFilterSelect;
const ratings = require('./ratings');
const router = express.Router();

router.post("/register", register);
router.post("/login", login);
router.post("/changepassword", loggedIn, changepassword);
router.post("/deleteaccount", loggedIn, deleteaccount);
router.post("/cars/brands", brands);
router.post("/cars/models", models);
router.post("/cars/engines", engines);
router.post("/category", category);
router.post("/parts", parts);
router.post("/parts/code", partsByCode);
router.post("/parts/brandSelect", brandsFilterSelect);
router.post("/ratings", ratings);

module.exports = router;